//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilaCocheras.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstacionaloEntities : DbContext
    {
        public EstacionaloEntities()
            : base("name=EstacionaloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Cochera> Cochera { get; set; }
        public DbSet<Propietario> Propietario { get; set; }
        public DbSet<Puntaje> Puntaje { get; set; }
        public DbSet<TipoPerfilUsuario> TipoPerfilUsuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
    }
}
