//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TP_20162CModel", "FK_Cocheras_Usuarios", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlquilaCocheras.Data.Usuarios), "Cocheras", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlquilaCocheras.Data.Cocheras), true)]
[assembly: EdmRelationshipAttribute("TP_20162CModel", "FK_Reservas_Cocheras", "Cocheras", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlquilaCocheras.Data.Cocheras), "Reservas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlquilaCocheras.Data.Reservas), true)]
[assembly: EdmRelationshipAttribute("TP_20162CModel", "FK_Reservas_Usuarios", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlquilaCocheras.Data.Usuarios), "Reservas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlquilaCocheras.Data.Reservas), true)]

#endregion

namespace AlquilaCocheras.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TP_20162CEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TP_20162CEntities object using the connection string found in the 'TP_20162CEntities' section of the application configuration file.
        /// </summary>
        public TP_20162CEntities() : base("name=TP_20162CEntities", "TP_20162CEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TP_20162CEntities object.
        /// </summary>
        public TP_20162CEntities(string connectionString) : base(connectionString, "TP_20162CEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TP_20162CEntities object.
        /// </summary>
        public TP_20162CEntities(EntityConnection connection) : base(connection, "TP_20162CEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cocheras> Cocheras
        {
            get
            {
                if ((_Cocheras == null))
                {
                    _Cocheras = base.CreateObjectSet<Cocheras>("Cocheras");
                }
                return _Cocheras;
            }
        }
        private ObjectSet<Cocheras> _Cocheras;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservas> Reservas
        {
            get
            {
                if ((_Reservas == null))
                {
                    _Reservas = base.CreateObjectSet<Reservas>("Reservas");
                }
                return _Reservas;
            }
        }
        private ObjectSet<Reservas> _Reservas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cocheras EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCocheras(Cocheras cocheras)
        {
            base.AddObject("Cocheras", cocheras);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservas(Reservas reservas)
        {
            base.AddObject("Reservas", reservas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP_20162CModel", Name="Cocheras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cocheras : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cocheras object.
        /// </summary>
        /// <param name="idCochera">Initial value of the IdCochera property.</param>
        /// <param name="idPropietario">Initial value of the IdPropietario property.</param>
        /// <param name="ubicacion">Initial value of the Ubicacion property.</param>
        /// <param name="fechaInicio">Initial value of the FechaInicio property.</param>
        /// <param name="fechaFin">Initial value of the FechaFin property.</param>
        /// <param name="horaInicio">Initial value of the HoraInicio property.</param>
        /// <param name="horaFin">Initial value of the HoraFin property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="latitud">Initial value of the Latitud property.</param>
        /// <param name="longitud">Initial value of the Longitud property.</param>
        /// <param name="metrosCuadrados">Initial value of the MetrosCuadrados property.</param>
        /// <param name="tipoVehiculo">Initial value of the TipoVehiculo property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="imagen">Initial value of the Imagen property.</param>
        public static Cocheras CreateCocheras(global::System.Int32 idCochera, global::System.Int32 idPropietario, global::System.String ubicacion, global::System.DateTime fechaInicio, global::System.DateTime fechaFin, global::System.String horaInicio, global::System.String horaFin, global::System.String descripcion, global::System.Decimal latitud, global::System.Decimal longitud, global::System.Int32 metrosCuadrados, global::System.Int16 tipoVehiculo, global::System.Decimal precio, global::System.String imagen)
        {
            Cocheras cocheras = new Cocheras();
            cocheras.IdCochera = idCochera;
            cocheras.IdPropietario = idPropietario;
            cocheras.Ubicacion = ubicacion;
            cocheras.FechaInicio = fechaInicio;
            cocheras.FechaFin = fechaFin;
            cocheras.HoraInicio = horaInicio;
            cocheras.HoraFin = horaFin;
            cocheras.Descripcion = descripcion;
            cocheras.Latitud = latitud;
            cocheras.Longitud = longitud;
            cocheras.MetrosCuadrados = metrosCuadrados;
            cocheras.TipoVehiculo = tipoVehiculo;
            cocheras.Precio = precio;
            cocheras.Imagen = imagen;
            return cocheras;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCochera
        {
            get
            {
                return _IdCochera;
            }
            set
            {
                if (_IdCochera != value)
                {
                    OnIdCocheraChanging(value);
                    ReportPropertyChanging("IdCochera");
                    _IdCochera = StructuralObject.SetValidValue(value, "IdCochera");
                    ReportPropertyChanged("IdCochera");
                    OnIdCocheraChanged();
                }
            }
        }
        private global::System.Int32 _IdCochera;
        partial void OnIdCocheraChanging(global::System.Int32 value);
        partial void OnIdCocheraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPropietario
        {
            get
            {
                return _IdPropietario;
            }
            set
            {
                OnIdPropietarioChanging(value);
                ReportPropertyChanging("IdPropietario");
                _IdPropietario = StructuralObject.SetValidValue(value, "IdPropietario");
                ReportPropertyChanged("IdPropietario");
                OnIdPropietarioChanged();
            }
        }
        private global::System.Int32 _IdPropietario;
        partial void OnIdPropietarioChanging(global::System.Int32 value);
        partial void OnIdPropietarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ubicacion
        {
            get
            {
                return _Ubicacion;
            }
            set
            {
                OnUbicacionChanging(value);
                ReportPropertyChanging("Ubicacion");
                _Ubicacion = StructuralObject.SetValidValue(value, false, "Ubicacion");
                ReportPropertyChanged("Ubicacion");
                OnUbicacionChanged();
            }
        }
        private global::System.String _Ubicacion;
        partial void OnUbicacionChanging(global::System.String value);
        partial void OnUbicacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value, "FechaInicio");
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private global::System.DateTime _FechaInicio;
        partial void OnFechaInicioChanging(global::System.DateTime value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value, "FechaFin");
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private global::System.DateTime _FechaFin;
        partial void OnFechaFinChanging(global::System.DateTime value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraInicio
        {
            get
            {
                return _HoraInicio;
            }
            set
            {
                OnHoraInicioChanging(value);
                ReportPropertyChanging("HoraInicio");
                _HoraInicio = StructuralObject.SetValidValue(value, false, "HoraInicio");
                ReportPropertyChanged("HoraInicio");
                OnHoraInicioChanged();
            }
        }
        private global::System.String _HoraInicio;
        partial void OnHoraInicioChanging(global::System.String value);
        partial void OnHoraInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraFin
        {
            get
            {
                return _HoraFin;
            }
            set
            {
                OnHoraFinChanging(value);
                ReportPropertyChanging("HoraFin");
                _HoraFin = StructuralObject.SetValidValue(value, false, "HoraFin");
                ReportPropertyChanged("HoraFin");
                OnHoraFinChanged();
            }
        }
        private global::System.String _HoraFin;
        partial void OnHoraFinChanging(global::System.String value);
        partial void OnHoraFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitud
        {
            get
            {
                return _Latitud;
            }
            set
            {
                OnLatitudChanging(value);
                ReportPropertyChanging("Latitud");
                _Latitud = StructuralObject.SetValidValue(value, "Latitud");
                ReportPropertyChanged("Latitud");
                OnLatitudChanged();
            }
        }
        private global::System.Decimal _Latitud;
        partial void OnLatitudChanging(global::System.Decimal value);
        partial void OnLatitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitud
        {
            get
            {
                return _Longitud;
            }
            set
            {
                OnLongitudChanging(value);
                ReportPropertyChanging("Longitud");
                _Longitud = StructuralObject.SetValidValue(value, "Longitud");
                ReportPropertyChanged("Longitud");
                OnLongitudChanged();
            }
        }
        private global::System.Decimal _Longitud;
        partial void OnLongitudChanging(global::System.Decimal value);
        partial void OnLongitudChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MetrosCuadrados
        {
            get
            {
                return _MetrosCuadrados;
            }
            set
            {
                OnMetrosCuadradosChanging(value);
                ReportPropertyChanging("MetrosCuadrados");
                _MetrosCuadrados = StructuralObject.SetValidValue(value, "MetrosCuadrados");
                ReportPropertyChanged("MetrosCuadrados");
                OnMetrosCuadradosChanged();
            }
        }
        private global::System.Int32 _MetrosCuadrados;
        partial void OnMetrosCuadradosChanging(global::System.Int32 value);
        partial void OnMetrosCuadradosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TipoVehiculo
        {
            get
            {
                return _TipoVehiculo;
            }
            set
            {
                OnTipoVehiculoChanging(value);
                ReportPropertyChanging("TipoVehiculo");
                _TipoVehiculo = StructuralObject.SetValidValue(value, "TipoVehiculo");
                ReportPropertyChanged("TipoVehiculo");
                OnTipoVehiculoChanged();
            }
        }
        private global::System.Int16 _TipoVehiculo;
        partial void OnTipoVehiculoChanging(global::System.Int16 value);
        partial void OnTipoVehiculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, "Precio");
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Decimal _Precio;
        partial void OnPrecioChanging(global::System.Decimal value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Imagen
        {
            get
            {
                return _Imagen;
            }
            set
            {
                OnImagenChanging(value);
                ReportPropertyChanging("Imagen");
                _Imagen = StructuralObject.SetValidValue(value, false, "Imagen");
                ReportPropertyChanged("Imagen");
                OnImagenChanged();
            }
        }
        private global::System.String _Imagen;
        partial void OnImagenChanging(global::System.String value);
        partial void OnImagenChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Cocheras_Usuarios", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Cocheras_Usuarios", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Cocheras_Usuarios", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Cocheras_Usuarios", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("TP_20162CModel.FK_Cocheras_Usuarios", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Reservas_Cocheras", "Reservas")]
        public EntityCollection<Reservas> Reservas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservas>("TP_20162CModel.FK_Reservas_Cocheras", "Reservas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservas>("TP_20162CModel.FK_Reservas_Cocheras", "Reservas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP_20162CModel", Name="Reservas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reservas object.
        /// </summary>
        /// <param name="idReserva">Initial value of the IdReserva property.</param>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="idCochera">Initial value of the IdCochera property.</param>
        /// <param name="fechaInicio">Initial value of the FechaInicio property.</param>
        /// <param name="fechaFin">Initial value of the FechaFin property.</param>
        /// <param name="horaInicio">Initial value of the HoraInicio property.</param>
        /// <param name="horaFin">Initial value of the HoraFin property.</param>
        /// <param name="cantidadHoras">Initial value of the CantidadHoras property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="fechaCarga">Initial value of the FechaCarga property.</param>
        /// <param name="puntuacion">Initial value of the Puntuacion property.</param>
        public static Reservas CreateReservas(global::System.Int32 idReserva, global::System.Int32 idCliente, global::System.Int32 idCochera, global::System.DateTime fechaInicio, global::System.DateTime fechaFin, global::System.String horaInicio, global::System.String horaFin, global::System.Decimal cantidadHoras, global::System.Decimal precio, global::System.DateTime fechaCarga, global::System.Int16 puntuacion)
        {
            Reservas reservas = new Reservas();
            reservas.IdReserva = idReserva;
            reservas.IdCliente = idCliente;
            reservas.IdCochera = idCochera;
            reservas.FechaInicio = fechaInicio;
            reservas.FechaFin = fechaFin;
            reservas.HoraInicio = horaInicio;
            reservas.HoraFin = horaFin;
            reservas.CantidadHoras = cantidadHoras;
            reservas.Precio = precio;
            reservas.FechaCarga = fechaCarga;
            reservas.Puntuacion = puntuacion;
            return reservas;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdReserva
        {
            get
            {
                return _IdReserva;
            }
            set
            {
                if (_IdReserva != value)
                {
                    OnIdReservaChanging(value);
                    ReportPropertyChanging("IdReserva");
                    _IdReserva = StructuralObject.SetValidValue(value, "IdReserva");
                    ReportPropertyChanged("IdReserva");
                    OnIdReservaChanged();
                }
            }
        }
        private global::System.Int32 _IdReserva;
        partial void OnIdReservaChanging(global::System.Int32 value);
        partial void OnIdReservaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value, "IdCliente");
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCochera
        {
            get
            {
                return _IdCochera;
            }
            set
            {
                OnIdCocheraChanging(value);
                ReportPropertyChanging("IdCochera");
                _IdCochera = StructuralObject.SetValidValue(value, "IdCochera");
                ReportPropertyChanged("IdCochera");
                OnIdCocheraChanged();
            }
        }
        private global::System.Int32 _IdCochera;
        partial void OnIdCocheraChanging(global::System.Int32 value);
        partial void OnIdCocheraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaInicio
        {
            get
            {
                return _FechaInicio;
            }
            set
            {
                OnFechaInicioChanging(value);
                ReportPropertyChanging("FechaInicio");
                _FechaInicio = StructuralObject.SetValidValue(value, "FechaInicio");
                ReportPropertyChanged("FechaInicio");
                OnFechaInicioChanged();
            }
        }
        private global::System.DateTime _FechaInicio;
        partial void OnFechaInicioChanging(global::System.DateTime value);
        partial void OnFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaFin
        {
            get
            {
                return _FechaFin;
            }
            set
            {
                OnFechaFinChanging(value);
                ReportPropertyChanging("FechaFin");
                _FechaFin = StructuralObject.SetValidValue(value, "FechaFin");
                ReportPropertyChanged("FechaFin");
                OnFechaFinChanged();
            }
        }
        private global::System.DateTime _FechaFin;
        partial void OnFechaFinChanging(global::System.DateTime value);
        partial void OnFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraInicio
        {
            get
            {
                return _HoraInicio;
            }
            set
            {
                OnHoraInicioChanging(value);
                ReportPropertyChanging("HoraInicio");
                _HoraInicio = StructuralObject.SetValidValue(value, false, "HoraInicio");
                ReportPropertyChanged("HoraInicio");
                OnHoraInicioChanged();
            }
        }
        private global::System.String _HoraInicio;
        partial void OnHoraInicioChanging(global::System.String value);
        partial void OnHoraInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoraFin
        {
            get
            {
                return _HoraFin;
            }
            set
            {
                OnHoraFinChanging(value);
                ReportPropertyChanging("HoraFin");
                _HoraFin = StructuralObject.SetValidValue(value, false, "HoraFin");
                ReportPropertyChanged("HoraFin");
                OnHoraFinChanged();
            }
        }
        private global::System.String _HoraFin;
        partial void OnHoraFinChanging(global::System.String value);
        partial void OnHoraFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CantidadHoras
        {
            get
            {
                return _CantidadHoras;
            }
            set
            {
                OnCantidadHorasChanging(value);
                ReportPropertyChanging("CantidadHoras");
                _CantidadHoras = StructuralObject.SetValidValue(value, "CantidadHoras");
                ReportPropertyChanged("CantidadHoras");
                OnCantidadHorasChanged();
            }
        }
        private global::System.Decimal _CantidadHoras;
        partial void OnCantidadHorasChanging(global::System.Decimal value);
        partial void OnCantidadHorasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value, "Precio");
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Decimal _Precio;
        partial void OnPrecioChanging(global::System.Decimal value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCarga
        {
            get
            {
                return _FechaCarga;
            }
            set
            {
                OnFechaCargaChanging(value);
                ReportPropertyChanging("FechaCarga");
                _FechaCarga = StructuralObject.SetValidValue(value, "FechaCarga");
                ReportPropertyChanged("FechaCarga");
                OnFechaCargaChanged();
            }
        }
        private global::System.DateTime _FechaCarga;
        partial void OnFechaCargaChanging(global::System.DateTime value);
        partial void OnFechaCargaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Puntuacion
        {
            get
            {
                return _Puntuacion;
            }
            set
            {
                OnPuntuacionChanging(value);
                ReportPropertyChanging("Puntuacion");
                _Puntuacion = StructuralObject.SetValidValue(value, "Puntuacion");
                ReportPropertyChanged("Puntuacion");
                OnPuntuacionChanged();
            }
        }
        private global::System.Int16 _Puntuacion;
        partial void OnPuntuacionChanging(global::System.Int16 value);
        partial void OnPuntuacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Reservas_Cocheras", "Cocheras")]
        public Cocheras Cocheras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocheras>("TP_20162CModel.FK_Reservas_Cocheras", "Cocheras").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocheras>("TP_20162CModel.FK_Reservas_Cocheras", "Cocheras").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cocheras> CocherasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocheras>("TP_20162CModel.FK_Reservas_Cocheras", "Cocheras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cocheras>("TP_20162CModel.FK_Reservas_Cocheras", "Cocheras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Reservas_Usuarios", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Reservas_Usuarios", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Reservas_Usuarios", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("TP_20162CModel.FK_Reservas_Usuarios", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("TP_20162CModel.FK_Reservas_Usuarios", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP_20162CModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="contrasenia">Initial value of the Contrasenia property.</param>
        /// <param name="perfil">Initial value of the Perfil property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 idUsuario, global::System.String nombre, global::System.String apellido, global::System.String email, global::System.String contrasenia, global::System.Int16 perfil)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.IdUsuario = idUsuario;
            usuarios.Nombre = nombre;
            usuarios.Apellido = apellido;
            usuarios.Email = email;
            usuarios.Contrasenia = contrasenia;
            usuarios.Perfil = perfil;
            return usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value, "IdUsuario");
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false, "Apellido");
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contrasenia
        {
            get
            {
                return _Contrasenia;
            }
            set
            {
                OnContraseniaChanging(value);
                ReportPropertyChanging("Contrasenia");
                _Contrasenia = StructuralObject.SetValidValue(value, false, "Contrasenia");
                ReportPropertyChanged("Contrasenia");
                OnContraseniaChanged();
            }
        }
        private global::System.String _Contrasenia;
        partial void OnContraseniaChanging(global::System.String value);
        partial void OnContraseniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, "Perfil");
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.Int16 _Perfil;
        partial void OnPerfilChanging(global::System.Int16 value);
        partial void OnPerfilChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Cocheras_Usuarios", "Cocheras")]
        public EntityCollection<Cocheras> Cocheras
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cocheras>("TP_20162CModel.FK_Cocheras_Usuarios", "Cocheras");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cocheras>("TP_20162CModel.FK_Cocheras_Usuarios", "Cocheras", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP_20162CModel", "FK_Reservas_Usuarios", "Reservas")]
        public EntityCollection<Reservas> Reservas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservas>("TP_20162CModel.FK_Reservas_Usuarios", "Reservas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservas>("TP_20162CModel.FK_Reservas_Usuarios", "Reservas", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
