//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilaCocheras.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public Propietario()
        {
            this.Cochera = new HashSet<Cochera>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual ICollection<Cochera> Cochera { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
