//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlquilaCocheras.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntaje
    {
        public int Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> CantidadVotos { get; set; }
        public Nullable<int> IdCochera { get; set; }
    
        public virtual Cochera Cochera { get; set; }
    }
}
